ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TRAINER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FACILITATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PAYROLL';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'AUDITOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'READ_ONLY';
